// services/marketing/marketingDelivery.service.js
//
// THE STATE MACHINE BEHIND EVERY OUTBOUND PROJECTION.
//
// ── THE ORDER OF WRITES IS THE WHOLE DESIGN ────────────────────────────────
// An attempt is recorded BEFORE the remote call and resolved afterwards.
// Written the other way round — record the outcome once you have one — a
// process that dies mid-call leaves a row that has never attempted anything,
// and the person silently never syncs. Written this way, a crash leaves
// `inFlightSince` set with no outcome, which is a visible, reportable state
// that says "somebody should look" rather than a gap that says nothing.
//
// Success is therefore never inferred from the absence of an error. It is only
// ever written by `recordSuccess`, after Mautic has answered.
//
// ── CLASSIFY FROM CODES, NOT FROM MESSAGES ─────────────────────────────────
// Whether a failure is worth retrying is decided from the error's stable code.
// A message is prose somebody will reword, and a retry policy that depends on
// prose changes silently the first time somebody improves a sentence.
//
// ── AND A CLAIM IS AN ATOMIC UPDATE, NOT A CHECK ───────────────────────────
// Two workers scanning for due retries will both see the same row. A
// read-then-write claim is passed by both of them; a single
// `findOneAndUpdate` whose filter includes "not already claimed" is won by
// exactly one, because the database decides. That is the only reason a second
// worker cannot create a second Mautic contact for the same person.
//
// ── THE CLAIM IS ALSO A FENCE, NOT ONLY A GATE ─────────────────────────────
// Winning the claim was not enough. The settle operations originally updated by
// company and person alone and cleared the claim unconditionally, which leaves
// this open:
//
//   1. worker A claims;  2. A's lease expires while A is still running;
//   3. worker B claims;  4. B settles a newer result;
//   5. A finishes late and overwrites B's outcome and clears B's claim.
//
// So the lease token is carried through the attempt and required when settling
// one. A settle whose token no longer matches the row writes NOTHING and reports
// that it lost the lease. The token is internal — generated by `claimDue`,
// passed to the runner's `project()` and back into these functions — and is
// never accepted from an HTTP caller, because a fence a client can supply is a
// fence a client can forge.
"use strict";

const crypto = require("crypto");

const DeliveryState = require("../../models/CMS_Models/Marketing/MarketingDeliveryState");
const MarketingIdentity = require("../../models/CMS_Models/Marketing/MarketingIdentity");
const { fail } = require("../storePurchase/errors");
const { DELIVERY_RETRY } = require("../../constants/marketing");

const str = (v) => String(v ?? "").trim();

/* ── CLASSIFICATION ─────────────────────────────────────────────────────────
   Keyed on the stable codes raised by services/marketing/mauticClient.js,
   marketingConsent.service.js and the shared error table. An unlisted code is
   treated as TERMINAL, deliberately: an error nobody has classified is an error
   nobody understands, and retrying it for six hours teaches us nothing while
   hiding it behind a backlog. */
const CLASSIFICATION = Object.freeze({
  MAUTIC_UNAVAILABLE: { failureClass: "TRANSIENT", reasonCode: "MAUTIC_UNREACHABLE" },
  MAUTIC_AUTH_FAILED: { failureClass: "TERMINAL", reasonCode: "MAUTIC_AUTH_REFUSED" },
  MAUTIC_NOT_CONFIGURED: { failureClass: "TERMINAL", reasonCode: "MAUTIC_NOT_CONFIGURED" },
  MAUTIC_REJECTED_WRITE: { failureClass: "TERMINAL", reasonCode: "MAUTIC_WRITE_REJECTED" },
  MAUTIC_BAD_REQUEST: { failureClass: "TERMINAL", reasonCode: "MAUTIC_WRITE_REJECTED" },
  MARKETING_CONSENT_INELIGIBLE: { failureClass: "CONSENT", reasonCode: "CONSENT_INELIGIBLE" },
  MARKETING_CONSENT_CALLER_SUPPLIED: { failureClass: "TERMINAL", reasonCode: "PROJECTION_INVALID" },
  MARKETING_CONSENT_INVALID: { failureClass: "TERMINAL", reasonCode: "PROJECTION_INVALID" },
  VALIDATION: { failureClass: "TERMINAL", reasonCode: "PROJECTION_INVALID" },
  TENANT_MEMBERSHIP_UNPROVEN: { failureClass: "TERMINAL", reasonCode: "PROJECTION_INVALID" },
});

const TERMINAL_FALLBACK = Object.freeze({ failureClass: "TERMINAL", reasonCode: "PROJECTION_INVALID" });

function classify(err) {
  const code = str(err?.code);
  return CLASSIFICATION[code] || TERMINAL_FALLBACK;
}

/**
 * The operator-facing sentence for a failure.
 *
 * Taken from the error's own message, which every refusal in this codebase
 * already writes for a person, then bounded. Never a stack, never a provider
 * body: `details` on these errors carries only codes and field names by
 * construction, and the body was never attached to begin with.
 */
const safeMessage = (err) => str(err?.message).slice(0, 500);

/* ── BOUNDED DETERMINISTIC BACKOFF ─────────────────────────────────────────
   `BASE * 2^(retryCount - 1)`, capped. Deterministic so a reconciliation report
   can state when a retry is due and be right — no jitter, because the thing
   jitter protects against (a thundering herd of clients against a shared
   service) is not this: one GRAV instance projecting its own people at a rate
   the backoff already bounds. */
function backoffMsFor(retryCount) {
  const n = Math.max(1, Number(retryCount) || 1);
  const raw = DELIVERY_RETRY.BASE_MS * 2 ** (n - 1);
  return Math.min(raw, DELIVERY_RETRY.MAX_DELAY_MS);
}

/** The read-time health, with the scheduled state split by the clock. */
function effectiveHealth(row, now = new Date()) {
  if (!row) return "NEVER_ATTEMPTED";
  if (row.health !== "RETRY_SCHEDULED") return row.health;
  if (!row.nextAttemptAt) return "RETRY_SCHEDULED";
  return row.nextAttemptAt <= now ? "RETRY_DUE" : "RETRY_WAITING";
}

/* ── THE FENCE ──────────────────────────────────────────────────────────────
   With a token: settle only while this lease is still the one on the row.
   Without one (an ordinary, unclaimed projection): settle only while NO live
   lease exists, so a direct call cannot stamp on a worker's in-flight attempt.
   An expired lease nobody has reclaimed is not a conflict — its holder's result
   is still the only result — so it does not block either path. */
function fencedFilter(key, leaseToken, now) {
  if (str(leaseToken)) return { ...key, "claim.token": str(leaseToken) };
  return {
    ...key,
    $or: [
      { "claim.token": { $in: ["", null] } },
      { "claim.token": { $exists: false } },
      { "claim.expiresAt": { $lte: now } },
    ],
  };
}

/** What a settle returns when the lease moved on. No write happened. */
const LEASE_LOST = Object.freeze({ settled: false, reason: "LEASE_LOST" });

/**
 * Apply a settle under the fence.
 *
 * ── WHY THIS IS NOT SIMPLY AN UPSERT ────────────────────────────────────────
 * A fenced filter that matches nothing and an upsert are a bad pair: mongo tries
 * to INSERT, the unique index on (companyId, gravPersonKey) refuses, and a
 * lease that was merely lost surfaces as a duplicate-key crash. So the write
 * never upserts, and a miss is then diagnosed rather than guessed at — the row
 * is either absent (a first settle on a fresh row, which only an unfenced caller
 * can legitimately do) or present and owned by somebody else.
 */
async function applySettle(key, update, leaseToken, now) {
  const row = await DeliveryState.findOneAndUpdate(
    fencedFilter(key, leaseToken, now), update, { new: true },
  );
  if (row) return { settled: true, row: row.toObject() };

  const exists = await DeliveryState.exists(key);
  /* The row is there and this caller does not hold it. */
  if (exists) return LEASE_LOST;
  /* A holder of a lease on a row that does not exist holds nothing. */
  if (str(leaseToken)) return LEASE_LOST;

  try {
    const created = await DeliveryState.findOneAndUpdate(
      key, update, { new: true, upsert: true, setDefaultsOnInsert: true },
    );
    return { settled: true, row: created.toObject() };
  } catch (err) {
    /* Somebody created it between the check and the insert. Their row is the
       one that exists; this settle lost. */
    if (err?.code === 11000) return LEASE_LOST;
    throw err;
  }
}

function assertKey({ companyId, gravPersonKey }) {
  if (!companyId) {
    throw fail("TENANT_MEMBERSHIP_UNPROVEN", "Delivery state cannot be read or written without a company.");
  }
  if (!str(gravPersonKey)) {
    throw fail("VALIDATION", "Delivery state needs the canonical GRAV person key.", { field: "gravPersonKey" });
  }
  return { companyId, gravPersonKey: str(gravPersonKey) };
}

/* ═══ RECORDING AN ATTEMPT ═════════════════════════════════════════════════ */

/**
 * Open an attempt. Called before the remote call, always.
 *
 * Upserts the row, so a person's first failure is queryable even though no
 * mapping and no Mautic contact exist yet — which is the gap this whole model
 * was added to close.
 *
 * @returns {Promise<{attemptNo:number, row:object}>}
 */
async function beginAttempt({ companyId, gravPersonKey, leaseToken = "", now = new Date() } = {}) {
  const key = assertKey({ companyId, gravPersonKey });

  const row = await DeliveryState.findOneAndUpdate(
    str(leaseToken) ? { ...key, "claim.token": str(leaseToken) } : key,
    {
      $inc: { attempts: 1 },
      $set: {
        /* IN_FLIGHT, not NEVER_ATTEMPTED. An open attempt is a state of its own;
           leaving it at NEVER_ATTEMPTED while the attempt counter moved was both
           a contradiction the schema forbade and a lie a crashed worker left
           behind — reconciliation read the row as never projected. */
        health: "IN_FLIGHT",
        lastAttemptAt: now,
        inFlightSince: now,
        lastOutcome: null,
        /* An attempt in progress supersedes any schedule that produced it. The
           previous `lastSuccessfulSyncAt` is deliberately NOT cleared: a person
           who synchronised last week and whose update crashed today has still
           synchronised, and losing that would report them as never reached. */
        nextAttemptAt: null,
      },
      $setOnInsert: { ...key, retryCount: 0 },
    },
    { upsert: !str(leaseToken), new: true, setDefaultsOnInsert: true },
  );

  if (!row) return { ...LEASE_LOST, attemptNo: 0, row: null };
  return { settled: true, attemptNo: row.attempts, row: row.toObject() };
}

/**
 * Resolve an attempt as a success.
 *
 * Clears the active error, the retry schedule and the retry count — a success
 * is the end of a failure story, not a line appended to it — and records the
 * Mautic contact the person is now linked to.
 */
async function recordSuccess({
  companyId, gravPersonKey, mauticContactId = "", leaseToken = "", now = new Date(),
} = {}) {
  const key = assertKey({ companyId, gravPersonKey });

  const outcome = await applySettle(key, {
    $set: {
      health: "SYNCHRONIZED",
      lastOutcome: "SUCCESS",
      lastSuccessfulSyncAt: now,
      inFlightSince: null,
      retryCount: 0,
      nextAttemptAt: null,
      activeError: null,
      consentReasonCode: "",
      mauticContactId: str(mauticContactId),
      /* Cleared only because we still hold it — the fence above proved so. */
      claim: {},
    },
    $setOnInsert: key,
  }, leaseToken, now);

  if (!outcome.settled) return LEASE_LOST;
  return { settled: true, row: outcome.row, ...outcome.row };
}

/**
 * Resolve an attempt as a failure, and decide what happens next.
 *
 *   TRANSIENT  → RETRY_SCHEDULED with bounded backoff, until the attempt budget
 *                is spent, at which point it becomes BLOCKED_TERMINAL with
 *                RETRY_BUDGET_SPENT. "Retry transient failures" is not "retry
 *                for ever": a row that has failed eight times is telling us
 *                something a ninth attempt will not.
 *   TERMINAL   → BLOCKED_TERMINAL, preserved for review (product plan §10).
 *   CONSENT    → BLOCKED_CONSENT, which is not a fault and is never retried,
 *                because nothing GRAV does will change it — only the person can.
 */
async function recordFailure({
  companyId, gravPersonKey, error, leaseToken = "", now = new Date(),
} = {}) {
  const key = assertKey({ companyId, gravPersonKey });
  const { failureClass, reasonCode } = classify(error);

  const current = await DeliveryState.findOne(key).lean();

  /* Checked before the counters are computed as well as in the write filter:
     a stale worker must not even decide what the next retry count should be. */
  if (str(leaseToken) && str(current?.claim?.token) !== str(leaseToken)) {
    return LEASE_LOST;
  }
  const retryCount = failureClass === "TRANSIENT" ? (current?.retryCount || 0) + 1 : 0;
  const budgetSpent = failureClass === "TRANSIENT" && retryCount >= DELIVERY_RETRY.MAX_ATTEMPTS;

  let health;
  let nextAttemptAt = null;
  let effectiveReason = reasonCode;

  if (failureClass === "CONSENT") {
    health = "BLOCKED_CONSENT";
  } else if (failureClass === "TRANSIENT" && !budgetSpent) {
    health = "RETRY_SCHEDULED";
    nextAttemptAt = new Date(now.getTime() + backoffMsFor(retryCount));
  } else {
    health = "BLOCKED_TERMINAL";
    if (budgetSpent) effectiveReason = "RETRY_BUDGET_SPENT";
  }

  const activeError = {
    reasonCode: effectiveReason,
    sourceCode: str(error?.code),
    failureClass,
    message: safeMessage(error),
    at: now,
    attemptNo: current?.attempts || 0,
  };

  const outcome = await applySettle(key, {
    $set: {
      health,
      lastOutcome: "FAILURE",
      inFlightSince: null,
      retryCount,
      nextAttemptAt,
      activeError,
      /* Refreshed on every attempt, including to empty, so a row that was
         consent-blocked and is now merely unreachable does not keep showing a
         consent reason nobody re-checked. */
      consentReasonCode: failureClass === "CONSENT" ? str(error?.details?.reasonCode) : "",
      claim: {},
    },
    $setOnInsert: key,
  }, leaseToken, now);

  if (!outcome.settled) return LEASE_LOST;
  return { settled: true, row: outcome.row, ...outcome.row };
}

/* ═══ CLAIMING ═════════════════════════════════════════════════════════════ */

/**
 * Claim up to `limit` rows whose retry is due.
 *
 * ── WHY THIS IS A LOOP OF SINGLE ATOMIC UPDATES ──────────────────────────
 * `updateMany` would mark a batch claimed but cannot tell us WHICH rows it won,
 * and a second worker running the same `updateMany` a millisecond later would
 * win nothing and learn nothing. One `findOneAndUpdate` per row returns the row
 * it won, or null if somebody else won it, which is exactly the information a
 * worker needs. The cost is one round trip per item, on a backlog that is
 * bounded by the retry budget.
 *
 * The filter is the lock. A row is claimable only when it is scheduled, its time
 * has come, and no live claim exists — and because the filter and the write are
 * one operation, two workers cannot both satisfy it.
 */
async function claimDue({ companyId, limit = 25, now = new Date(), by = "retry-runner" } = {}) {
  if (!companyId) {
    throw fail("TENANT_MEMBERSHIP_UNPROVEN", "Delivery claims need a company.");
  }

  const claimed = [];
  for (let i = 0; i < Math.max(1, Math.min(limit, 200)); i++) {
    const token = crypto.randomBytes(12).toString("hex");
    const unclaimed = [
      { "claim.expiresAt": null },
      { "claim.expiresAt": { $exists: false } },
      { "claim.expiresAt": { $lte: now } },
    ];
    const staleBefore = new Date(now.getTime() - DELIVERY_RETRY.CLAIM_TTL_MS);

    const row = await DeliveryState.findOneAndUpdate(
      {
        companyId,
        $and: [
          { $or: unclaimed },
          {
            $or: [
              /* A scheduled retry whose time has come. */
              { health: "RETRY_SCHEDULED", nextAttemptAt: { $lte: now } },
              /* AND a crashed attempt. Its worker opened it and never settled
                 it; once the lease it was holding has expired, the row is nobody's
                 and would otherwise sit IN_FLIGHT for ever. Reclaiming it here is
                 what makes a crash recoverable rather than terminal. Safe because
                 the reclaim mints a NEW lease, so the original worker — if it is
                 somehow still alive — can no longer settle. */
              { health: "IN_FLIGHT", inFlightSince: { $lte: staleBefore } },
            ],
          },
        ],
      },
      {
        $set: {
          claim: { token, at: now, expiresAt: new Date(now.getTime() + DELIVERY_RETRY.CLAIM_TTL_MS), by: str(by) },
        },
      },
      { new: true, sort: { nextAttemptAt: 1, lastAttemptAt: 1, _id: 1 } },
    );
    if (!row) break;
    claimed.push({ ...row.toObject(), claimToken: token });
  }
  return claimed;
}

/** Give a claim back without changing the outcome — for a worker shutting down
 *  mid-backlog. Only the holder may release, so a stale worker cannot unlock a
 *  row another worker has since taken. */
async function releaseClaim({ companyId, gravPersonKey, claimToken } = {}) {
  const key = assertKey({ companyId, gravPersonKey });
  const r = await DeliveryState.updateOne(
    { ...key, "claim.token": str(claimToken) },
    { $set: { claim: {} } },
  );
  return r.modifiedCount === 1;
}

/* ═══ READS ════════════════════════════════════════════════════════════════ */

/** One person's delivery state, with the read-time health. */
async function stateFor({ companyId, gravPersonKey, now = new Date() } = {}) {
  const key = assertKey({ companyId, gravPersonKey });
  const row = await DeliveryState.findOne(key).lean();
  if (!row) {
    return {
      exists: false,
      health: "NEVER_ATTEMPTED",
      effectiveHealth: "NEVER_ATTEMPTED",
      reasonCode: "DELIVERY_NEVER_ATTEMPTED",
      attempts: 0,
      mauticContactId: "",
      lastAttemptAt: null,
      lastSuccessfulSyncAt: null,
      nextAttemptAt: null,
      row: null,
    };
  }
  return {
    exists: true,
    health: row.health,
    effectiveHealth: effectiveHealth(row, now),
    reasonCode: row.activeError?.reasonCode
      || (row.health === "SYNCHRONIZED" ? "DELIVERY_OK" : "DELIVERY_NEVER_ATTEMPTED"),
    attempts: row.attempts,
    retryCount: row.retryCount,
    mauticContactId: row.mauticContactId,
    lastAttemptAt: row.lastAttemptAt,
    lastSuccessfulSyncAt: row.lastSuccessfulSyncAt,
    nextAttemptAt: row.nextAttemptAt,
    inFlightSince: row.inFlightSince,
    row,
  };
}

/* ═══ THE RETRY RUNNER ═════════════════════════════════════════════════════
   A SEPARATE OPERATION FROM INSPECTION, on purpose. The reconciliation query is
   read-only so that looking at the backlog can never change it; this is the one
   thing that acts, and it has to be asked for. */

/**
 * Retry the due backlog for one company.
 *
 * Idempotent in the only sense that matters: it calls the same `syncContact`
 * that a first attempt does, which resolves consent from the canonical record
 * and follows the existing identity-mapping path — so a retry of a person who
 * was in fact already linked updates that contact rather than creating a second
 * one, and a retry of a person whose consent has since been withdrawn is
 * refused rather than forced through.
 *
 * `project` is injected so the runner can be tested against the Mautic contract
 * double, and so this module does not import the sync service that imports it.
 *
 * Never throws for one person's failure: a backlog in which one bad row stops
 * the other forty is a backlog nobody drains.
 */
async function runDueRetries({
  companyId, client, project, personFor, limit = 25, now = new Date(), by = "retry-runner",
} = {}) {
  if (typeof project !== "function") {
    throw fail("VALIDATION", "The retry runner needs a project() function.", { field: "project" });
  }
  if (typeof personFor !== "function") {
    throw fail("VALIDATION", "The retry runner needs a personFor() lookup.", { field: "personFor" });
  }

  const claimed = await claimDue({ companyId, limit, now, by });
  const summary = { claimed: claimed.length, succeeded: 0, failed: 0, skipped: 0, results: [] };

  for (const row of claimed) {
    const gravPersonKey = row.gravPersonKey;
    try {
      const person = await personFor({ companyId, gravPersonKey });
      if (!person) {
        /* Nothing to project. Recorded as a terminal refusal rather than
           released: a scheduled retry for a person we can no longer describe
           will never succeed, and leaving it scheduled is a backlog that never
           drains. */
        await recordFailure({
          companyId, gravPersonKey, now, leaseToken: row.claimToken,
          error: fail("VALIDATION", "No marketing identity holds contact details for this person any more.", {}),
        });
        summary.skipped += 1;
        summary.results.push({ gravPersonKey, outcome: "SKIPPED", reasonCode: "PROJECTION_INVALID" });
        continue;
      }

      /* The lease travels with the work. `project` is the instrumented sync
         path, which passes it to every settle so a worker whose lease expired
         mid-flight writes nothing. Named with a double underscore because it is
         internal plumbing, not a parameter any caller — least of all an HTTP one
         — may supply. */
      const out = await project({
        client, companyId, gravPersonKey, person, __leaseToken: row.claimToken,
      });
      summary.succeeded += 1;
      summary.results.push({ gravPersonKey, outcome: "SUCCESS", engineContactRef: out?.contactId || "" });
    } catch (err) {
      /* `project` is the instrumented sync path, so it has already written the
         failure state. This only tallies it — writing it again here would
         double-count the attempt. */
      summary.failed += 1;
      summary.results.push({
        gravPersonKey, outcome: "FAILURE",
        reasonCode: classify(err).reasonCode, sourceCode: str(err?.code),
      });
    }
  }

  return summary;
}

/** The identity row's contact details, for the retry runner. Read-only, and
 *  company-scoped like everything else. */
async function personFromIdentity({ companyId, gravPersonKey } = {}) {
  const key = assertKey({ companyId, gravPersonKey });
  const row = await MarketingIdentity.findOne(key).lean();
  if (!row?.email) return null;
  return { workEmail: row.email };
}

module.exports = {
  beginAttempt, recordSuccess, recordFailure, fencedFilter, LEASE_LOST,
  claimDue, releaseClaim,
  stateFor, effectiveHealth, classify, backoffMsFor, safeMessage,
  runDueRetries, personFromIdentity,
  CLASSIFICATION,
};
