// models/CMS_Models/Inventory/Operations/MrfChatMessage.js
//
// One chat thread per MRF. Both sides of the conversation reach it through the
// backend, because they authenticate differently:
//   • cowork (requester / TL)  → Firebase ID token, verifyCoworkToken
//   • CMS store               → JWT cookie, EmployeeAuthMiddleware
// Messages therefore live in Mongo next to the MRF rather than in Firestore,
// and live delivery goes over the Socket.IO room `mrf_<mrfId>`.

const mongoose = require("mongoose");

const attachmentSchema = new mongoose.Schema(
  {
    url: { type: String, trim: true, required: true },
    publicId: { type: String, trim: true, default: "" },
    name: { type: String, trim: true, default: "" },
    type: { type: String, trim: true, default: "image" },
  },
  { _id: false }
);

const mrfChatMessageSchema = new mongoose.Schema(
  {
    // What this thread is attached to. Both material requests and
    // new-product requests need a conversation, and they live in different
    // collections, so the thread points at whichever one it belongs to.
    subjectType: {
      type: String,
      enum: ["MRF", "PRODUCT_REQUEST"],
      default: "MRF",
    },
    subject: { type: mongoose.Schema.Types.ObjectId, index: true },

    // Legacy field, kept populated for MRF threads so messages written before
    // subjectType existed still resolve. Reads match on either.
    mrf: { type: mongoose.Schema.Types.ObjectId, ref: "MRF", index: true, default: null },
    mrfNumber: { type: String, trim: true, default: "" },

    // Sender identity. senderBiometricId is set for cowork users (requester /
    // TL) and is what cowork notification routing keys on; store users have a
    // Mongo _id only.
    senderRef: { type: mongoose.Schema.Types.ObjectId, default: null },
    senderBiometricId: { type: String, trim: true, default: "" },
    senderName: { type: String, trim: true, default: "" },
    senderRole: {
      type: String,
      enum: ["employee", "tl", "store", "ceo", "system"],
      default: "employee",
    },

    body: { type: String, trim: true, default: "" },
    attachments: { type: [attachmentSchema], default: [] },

    // System messages are generated by status transitions (approved, issued,
    // marked unavailable…) so the thread reads as a complete history rather
    // than starting mid-conversation.
    isSystem: { type: Boolean, default: false },

    // Biometric ids (cowork) or Mongo _id strings (store) that have read it.
    readBy: { type: [String], default: [] },
  },
  { timestamps: true }
);

mrfChatMessageSchema.index({ mrf: 1, createdAt: 1 });
mrfChatMessageSchema.index({ subject: 1, createdAt: 1 });

module.exports =
  mongoose.models.MrfChatMessage ||
  mongoose.model("MrfChatMessage", mrfChatMessageSchema);
