// models/CMS_Models/Inventory/Operations/MrfChatMessage.js
//
// One chat thread per MRF. Both sides of the conversation reach it through the
// backend, because they authenticate differently:
//   • cowork (requester / TL)  → Firebase ID token, verifyCoworkToken
//   • CMS store               → JWT cookie, EmployeeAuthMiddleware
// Messages therefore live in Mongo next to the MRF rather than in Firestore,
// and live delivery goes over the Socket.IO room `mrf_<mrfId>`.

const mongoose = require("mongoose");

/* An attachment is part of a message and has no separate owner: it is reached
   only through the message, so scoping it independently protects nothing and
   invites the two from disagreeing. Ownership lives on the message below. */
const attachmentSchema = new mongoose.Schema(
  {
    url: { type: String, trim: true, required: true },
    publicId: { type: String, trim: true, default: "" },
    name: { type: String, trim: true, default: "" },
    type: { type: String, trim: true, default: "image" },
  },
  { _id: false }
);

const mrfChatMessageSchema = new mongoose.Schema(
  {
    // What this thread is attached to. Both material requests and
    // new-product requests need a conversation, and they live in different
    // collections, so the thread points at whichever one it belongs to.
    subjectType: {
      type: String,
      enum: ["MRF", "PRODUCT_REQUEST"],
      default: "MRF",
    },
    subject: { type: mongoose.Schema.Types.ObjectId, index: true },

    /* ── Tenant ownership ───────────────────────────────────────────────────
       A message inherits the company of the request it is about, taken from
       the authoritative parent document and never from a request payload.
       Optional for the same reason MRF.companyId is: messages written before
       the boundary existed carry none, and those are legacy-global — excluded
       from ordinary reads rather than adopted by whoever asks first. */
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Acc_Company",
      default: null,
      index: true,
    },
    siteId: { type: mongoose.Schema.Types.ObjectId, default: null },

    /* The key of the action that produced this message. A unique index over
       (companyId, subject, idempotencyKey) is what makes posting at-most-once:
       creation itself is the effect marker, so a retry collides here instead
       of writing a second message. Null for system messages and for anything
       written before chat was idempotent, which is why the index is partial. */
    idempotencyKey: { type: String, trim: true, default: null },

    // Legacy field, kept populated for MRF threads so messages written before
    // subjectType existed still resolve. Reads match on either.
    mrf: { type: mongoose.Schema.Types.ObjectId, ref: "MRF", index: true, default: null },
    mrfNumber: { type: String, trim: true, default: "" },

    // Sender identity. senderBiometricId is set for cowork users (requester /
    // TL) and is what cowork notification routing keys on; store users have a
    // Mongo _id only.
    senderRef: { type: mongoose.Schema.Types.ObjectId, default: null },
    senderBiometricId: { type: String, trim: true, default: "" },
    senderName: { type: String, trim: true, default: "" },
    senderRole: {
      type: String,
      enum: ["employee", "tl", "store", "ceo", "system"],
      default: "employee",
    },

    body: { type: String, trim: true, default: "" },
    attachments: { type: [attachmentSchema], default: [] },

    // System messages are generated by status transitions (approved, issued,
    // marked unavailable…) so the thread reads as a complete history rather
    // than starting mid-conversation.
    isSystem: { type: Boolean, default: false },

    // Biometric ids (cowork) or Mongo _id strings (store) that have read it.
    readBy: { type: [String], default: [] },
  },
  { timestamps: true }
);

mrfChatMessageSchema.index({ mrf: 1, createdAt: 1 });
mrfChatMessageSchema.index({ subject: 1, createdAt: 1 });
/* Company-scoped variants of the two hot paths, so a scoped read is not a
   prefix mismatch against the indexes above. */
/* Company-scoped variants of the two hot paths, so a scoped read is not a
   prefix mismatch against the indexes above. */
mrfChatMessageSchema.index({ companyId: 1, subject: 1, createdAt: 1 });
mrfChatMessageSchema.index({ companyId: 1, mrf: 1, createdAt: 1 });

/* At-most-once posting. Partial so the millions of messages with no key do not
   collide with each other on null. */
mrfChatMessageSchema.index(
  { companyId: 1, subject: 1, idempotencyKey: 1 },
  {
    unique: true,
    partialFilterExpression: { idempotencyKey: { $type: "string" } },
    name: "sp_chat_idempotency",
  },
);

module.exports =
  mongoose.models.MrfChatMessage ||
  mongoose.model("MrfChatMessage", mrfChatMessageSchema);
