/**
 * Employee Import / Export Routes
 * Mount at: /api/employees/import-export
 *
 * GET  /template          → download static .xlsx template
 * POST /import/preview    → parse uploaded .xlsx → structured preview
 * POST /import/confirm    → save to MongoDB
 * GET  /export            → export employees as styled .xlsx (re-importable)
 *
 * EXPORT FORMAT
 * -------------
 * The exported file uses the EXACT same column layout as the import template
 * (employee_import_filled_main format) so that export → re-import is lossless.
 * Salary auto-calc fields get live Excel formulas so the file is also usable
 * as a reference / payroll document.
 *
 * DYNAMIC EXTRA COLUMNS
 * ---------------------
 * Any column in the Excel that is NOT in the standard HEADER_MAP is checked
 * against EXTRA_FIELD_MAP. If matched, the value is applied to the correct
 * Employee schema field automatically.
 */

const fs = require("fs");
const path = require("path");
const express = require("express");
const router = express.Router();
const multer = require("multer");
// xlsx READS uploads well. It cannot WRITE styles — the community build drops
// them silently — so anything this file produces goes through ExcelJS instead.
const XLSX = require("xlsx");
const ExcelJS = require("exceljs");
const Employee = require("../../models/Employee");
const SalaryConfig = require("../../models/Salaryconfig");
// Salary is AES-encrypted at rest. Anything that READS a salary for display
// has to decrypt first, and anything that WRITES one has to go through the
// model's pre-save hook so it is re-encrypted.
const { decryptEmployeeDoc, decryptEmployeeDocs } = require("../../utils/salaryEncryption");
const EmployeeAuthMiddlewear = require("../../Middlewear/EmployeeAuthMiddlewear");

// The workbook everything is generated from. This file IS the design: banner,
// section colours, borders, column widths, freeze panes and the Instructions
// sheet all live in it. Restyle the download by editing this file — nothing in
// the code needs to change, and the template and the export cannot drift apart
// because both are built from it.
const TEMPLATE_PATH = path.join(__dirname, "../../assets/employee_import_template.xlsx");

/**
 * Refuse to send anything that is not a real workbook.
 *
 * .xlsx is a zip, so a valid one always starts with the bytes "PK". A zero-byte
 * or truncated body reaches the user as Excel's "the file format or file
 * extension is not valid" with nothing anywhere to explain it — which is
 * exactly how the original broken template presented. A 500 with a message is
 * something someone can actually act on.
 */
function assertRealWorkbook(buffer, label) {
    if (!Buffer.isBuffer(buffer) || buffer.length === 0) {
        throw new Error(`Generated ${label} is empty — nothing was written.`);
    }
    if (buffer.slice(0, 2).toString("latin1") !== "PK") {
        throw new Error(
            `Generated ${label} is not a valid .xlsx (missing zip signature).`,
        );
    }
}

// ── multer ────────────────────────────────────────────────────────────────────
const upload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 10 * 1024 * 1024 },
    fileFilter: (req, file, cb) => {
        // CSV is accepted because both /template and /export can hand one out
        // — refusing it back would be a dead end. XLSX.read parses it fine, and
        // findHeaderRow copes with the header sitting on row 1 rather than 3.
        const name = String(file.originalname || "").toLowerCase();
        const ok =
            file.mimetype.includes("spreadsheet") ||
            file.mimetype.includes("excel") ||
            file.mimetype.includes("csv") ||
            name.endsWith(".xlsx") ||
            name.endsWith(".xls") ||
            name.endsWith(".csv");
        cb(ok ? null : new Error("Only .xlsx, .xls or .csv files are allowed"), ok);
    },
});

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 1: DOWNLOAD TEMPLATE
//
// The template used to be a static file shipped in the repo. That file was
// 0 bytes, which is why Excel refused it with "the file format or file
// extension is not valid" — an empty file is not a zip, and .xlsx is a zip.
//
// It is now generated by the SAME builder as /export, so two problems go away
// at once: it cannot be missing or truncated, and the template's columns are
// by construction identical to what export produces. Export → edit → import
// round-trips because there is only one layout in the codebase.
//
// ?format=csv returns the same columns as plain CSV, for anyone whose Excel is
// unhappy with xlsx.
// ─────────────────────────────────────────────────────────────────────────────
router.get("/template", EmployeeAuthMiddlewear, async (req, res) => {
    try {
        const cfg = await SalaryConfig.getSingleton();
        const wantsCsv = String(req.query.format || "").toLowerCase() === "csv";

        const built = await buildEmployeeWorkbook({
            employees: [],
            cfg,
            mode: "template",
            // Enough blank rows to type into, each already carrying the salary
            // formulas so Basic/HRA/EPF/CTC fill themselves in as Gross is typed.
            blankRows: 200,
        });

        // This URL has no query string, so it is trivially cacheable — and the
        // version that used to live here returned a 0-byte body. A browser or
        // proxy holding that response will keep handing out the broken file
        // long after the server is fixed, which looks exactly like the server
        // still being broken.
        res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate");
        res.setHeader("Pragma", "no-cache");
        res.setHeader("Expires", "0");

        if (wantsCsv) {
            res.setHeader("Content-Disposition", "attachment; filename=employee_import_template.csv");
            res.setHeader("Content-Type", "text/csv; charset=utf-8");
            return res.send(built.csv);
        }

        // Never ship a body that is not a real workbook. An .xlsx is a zip, so
        // it must start with "PK". Sending a truncated or empty body produces
        // Excel's "the file format or file extension is not valid", with
        // nothing in the logs to explain it — a JSON error is far easier to act
        // on than a corrupt download.
        assertRealWorkbook(built.buffer, "template");

        res.setHeader("Content-Disposition", "attachment; filename=employee_import_template.xlsx");
        res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        res.setHeader("Content-Length", built.buffer.length);
        return res.send(built.buffer);
    } catch (err) {
        console.error("Template download error:", err);
        res.status(500).json({ success: false, message: err.message || "Could not build the template." });
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// COLUMN DEFINITIONS
// This single array drives both import parsing and export generation.
// Keeping them in sync guarantees export → re-import is always lossless.
//
// Each entry:
//   header      — exact text shown in row 3 (column-header row)
//   field       — internal key used during import parsing
//   section     — which row-2 section banner this column belongs to
//   skip        — if true, column is auto-calculated (formulas, not raw data)
//   required    — adds " *" suffix to header and validates during import
// ─────────────────────────────────────────────────────────────────────────────
const COLUMNS = [
    // ── BASIC DETAILS ─────────────────────────────────────────────────────
    { header: "Employee Name", field: "employeeName", section: "BASIC DETAILS", required: true },
    { header: "Title", field: "title", section: "BASIC DETAILS" },
    { header: "Father / Husband Name", field: "fatherName", section: "BASIC DETAILS" },
    { header: "Gender", field: "gender", section: "BASIC DETAILS", required: true },
    { header: "Date of Birth", field: "dateOfBirth", section: "BASIC DETAILS" },
    { header: "Mobile Number", field: "phone", section: "BASIC DETAILS", required: true },
    { header: "Alternate Phone", field: "alternatePhone", section: "BASIC DETAILS" },
    { header: "Personal Email", field: "personalEmail", section: "BASIC DETAILS" },
    { header: "Work Email", field: "workEmail", section: "BASIC DETAILS" },
    { header: "Marital Status", field: "maritalStatus", section: "BASIC DETAILS" },
    { header: "Blood Group", field: "bloodGroup", section: "BASIC DETAILS" },
    { header: "Nationality", field: "nationality", section: "BASIC DETAILS" },
    { header: "Physically Challenged", field: "physicallyChallenged", section: "BASIC DETAILS" },
    // ── ADDRESS ───────────────────────────────────────────────────────────
    { header: "Street / Area", field: "currStreet", section: "ADDRESS" },
    { header: "City", field: "currCity", section: "ADDRESS" },
    { header: "State", field: "currState", section: "ADDRESS" },
    { header: "Pincode", field: "currPincode", section: "ADDRESS" },
    // ── EMPLOYMENT DETAILS ────────────────────────────────────────────────
    { header: "Biometric ID", field: "biometricId", section: "EMPLOYMENT DETAILS", required: true },
    { header: "Date of Joining", field: "dateOfJoining", section: "EMPLOYMENT DETAILS" },
    { header: "Department", field: "department", section: "EMPLOYMENT DETAILS", required: true },
    { header: "Designation", field: "designation", section: "EMPLOYMENT DETAILS", required: true },
    { header: "Employee Type", field: "employeeType", section: "EMPLOYMENT DETAILS" },
    { header: "Work Location", field: "workLocation", section: "EMPLOYMENT DETAILS" },
    { header: "Shift", field: "shift", section: "EMPLOYMENT DETAILS" },
    { header: "Is Director", field: "isDirector", section: "EMPLOYMENT DETAILS" },
    { header: "Needs to Operate", field: "needsToOperate", section: "EMPLOYMENT DETAILS" },
    // ── BANK DETAILS ──────────────────────────────────────────────────────
    { header: "Bank Name", field: "bankName", section: "BANK DETAILS" },
    { header: "Account Number", field: "accountNumber", section: "BANK DETAILS" },
    { header: "IFSC Code", field: "ifscCode", section: "BANK DETAILS" },
    { header: "Account Type", field: "accountType", section: "BANK DETAILS" },
    // ── SALARY DETAILS ────────────────────────────────────────────────────
    { header: "Gross Salary", field: "grossSalary", section: "SALARY DETAILS", required: true },
    { header: "Basic Salary", field: "_skip", section: "SALARY DETAILS", formula: true },
    { header: "HRA", field: "_skip", section: "SALARY DETAILS", formula: true },
    { header: "EPF (Employee)", field: "_skip", section: "SALARY DETAILS", formula: true },
    { header: "ESIC (Employee)", field: "_skip", section: "SALARY DETAILS", formula: true },
    { header: "Total Deductions", field: "_skip", section: "SALARY DETAILS", formula: true },
    { header: "Net Salary", field: "_skip", section: "SALARY DETAILS", formula: true },
    { header: "EPF (Employer)", field: "_skip", section: "SALARY DETAILS", formula: true },
    { header: "ESIC (Employer)", field: "_skip", section: "SALARY DETAILS", formula: true },
    { header: "Food Allowance", field: "_skip", section: "SALARY DETAILS", formula: true },
    { header: "Employer Cost (CTC)", field: "_skip", section: "SALARY DETAILS", formula: true },
    // ── STATUTORY DETAILS ─────────────────────────────────────────────────
    { header: "Aadhaar Number", field: "aadhaarNumber", section: "STATUTORY DETAILS" },
    { header: "PAN Number", field: "panNumber", section: "STATUTORY DETAILS" },
    { header: "UAN Number", field: "uanNumber", section: "STATUTORY DETAILS" },
    { header: "ESI Number", field: "esiNumber", section: "STATUTORY DETAILS" },
    { header: "PF Number", field: "pfNumber", section: "STATUTORY DETAILS" },
];

// Column indices (0-based) for quick lookup
const colIndex = {};
COLUMNS.forEach((col, i) => { colIndex[col.header] = i; });

// ─────────────────────────────────────────────────────────────────────────────
// STANDARD HEADER MAP (for import — derived from COLUMNS above)
// ─────────────────────────────────────────────────────────────────────────────
const HEADER_MAP = {};
COLUMNS.forEach(col => {
    HEADER_MAP[col.header] = col.field;
});

// ─────────────────────────────────────────────────────────────────────────────
// EXTRA / OPTIONAL FIELD MAP
// ─────────────────────────────────────────────────────────────────────────────
const EXTRA_FIELD_MAP = {
    "Nick Name": { field: "nickName", type: "string" },
    "Place Of Birth": { field: "placeOfBirth", type: "string" },
    "Place of Birth": { field: "placeOfBirth", type: "string" },
    "Residential Status": { field: "residentialStatus", type: "string" },
    "Religion": { field: "religion", type: "string" },
    "Country Of Origin": { field: "countryOfOrigin", type: "string" },
    "Country of Origin": { field: "countryOfOrigin", type: "string" },
    "Spouse Name": { field: "spouseName", type: "string" },
    "Marriage Date": { field: "marriageDate", type: "date" },
    "Spouse DOB": { field: "spouseDOB", type: "date" },
    "Mother First Name": { field: "motherFirstName", type: "string" },
    "Mother Last Name": { field: "motherLastName", type: "string" },
    "Father Middle Name": { field: "fatherMiddleName", type: "string" },
    "Is International": { field: "isInternational", type: "bool" },
    "Identity ID": { field: "identityId", type: "string" },
    "Job Position": { field: "jobPosition", type: "string" },
    "Job Title": { field: "jobTitle", type: "string" },
    "Confirmation Date": { field: "confirmationDate", type: "date" },
    "Probation Period": { field: "probationPeriod", type: "number" },
    "Probation Period (Months)": { field: "probationPeriod", type: "number" },
    "Extension": { field: "extension", type: "string" },
    "Branch Name": { field: "branchName", type: "string", nested: "bankDetails" },
    "Passport Number": { field: "passportNumber", type: "string" },
    "Voter ID": { field: "voterIdNumber", type: "string" },
    "Driving License": { field: "drivingLicenseNumber", type: "string" },
    "Primary Manager": { field: "primaryManagerName", type: "string" },
    "Secondary Manager": { field: "secondaryManagerName", type: "string" },
};

// ─────────────────────────────────────────────────────────────────────────────
// SECTION STYLING CONFIG
// ─────────────────────────────────────────────────────────────────────────────
const SECTION_STYLES = {
    "BASIC DETAILS": { bg: "3B82F6", text: "FFFFFF" }, // blue
    "ADDRESS": { bg: "0891B2", text: "FFFFFF" }, // cyan
    "EMPLOYMENT DETAILS": { bg: "5B21B6", text: "FFFFFF" }, // purple
    "BANK DETAILS": { bg: "0F766E", text: "FFFFFF" }, // teal
    "SALARY DETAILS": { bg: "059669", text: "FFFFFF" }, // green
    "STATUTORY DETAILS": { bg: "DC2626", text: "FFFFFF" }, // red
};

// Column header row background — required cols get light purple, others get light gray
// Formula/auto cols get light green
const getColHeaderBg = (col) => {
    if (col.formula) return "ECFDF5";  // light green for auto-calc
    if (col.required) return "EDE9FE"; // light purple for required
    return "F3F4F6";                   // light gray for optional
};

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────
const normalizeHeader = (h) =>
    String(h || "")
        .replace(/\n/g, " ")
        .replace(/\s+/g, " ")
        .replace(/\s*\*\s*$/, "")
        .trim();

const parseDate = (val) => {
    if (!val) return undefined;
    if (val instanceof Date) return isNaN(val.getTime()) ? undefined : val;
    if (typeof val === "number") {
        const p = XLSX.SSF.parse_date_code(val);
        return p ? new Date(p.y, p.m - 1, p.d) : undefined;
    }
    const s = String(val).trim();
    if (!s) return undefined;
    const m1 = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
    if (m1) return new Date(`${m1[3]}-${m1[2].padStart(2, "0")}-${m1[1].padStart(2, "0")}`);
    const m2 = s.match(/^(\d{1,2})-(\d{1,2})-(\d{4})$/);
    if (m2) return new Date(`${m2[3]}-${m2[2].padStart(2, "0")}-${m2[1].padStart(2, "0")}`);
    const d = new Date(s);
    return isNaN(d.getTime()) ? undefined : d;
};

const toNum = (v) => {
    if (typeof v === "number") return isNaN(v) ? 0 : v;
    const s = String(v || "").replace(/[,₹\s]/g, "");
    const n = Number(s);
    return isNaN(n) ? 0 : n;
};

const toBool = (v) => {
    if (typeof v === "boolean") return v;
    return String(v || "").toLowerCase().trim() === "yes";
};

/**
 * Yes/No that stays UNDECIDED when the cell is empty.
 *
 * toBool() turns a blank cell into `false`, which is right on a create and
 * destructive on an update: re-importing a sheet where "Is Director" was left
 * empty would quietly demote every director. undefined means "the sheet has no
 * opinion", and the merge skips it.
 */
const optBool = (v) => {
    if (typeof v === "boolean") return v;
    const s = String(v ?? "").trim().toLowerCase();
    if (!s) return undefined;
    if (["yes", "y", "true", "1"].includes(s)) return true;
    if (["no", "n", "false", "0"].includes(s)) return false;
    return undefined;
};

const isBlankValue = (v) =>
    v === undefined ||
    v === null ||
    (typeof v === "string" && v.trim() === "");

const sameValue = (a, b) => {
    if (a instanceof Date || b instanceof Date) {
        const ta = a instanceof Date ? a.getTime() : new Date(a).getTime();
        const tb = b instanceof Date ? b.getTime() : new Date(b).getTime();
        return ta === tb;
    }
    if (typeof a === "number" || typeof b === "number") return Number(a) === Number(b);
    if (typeof a === "boolean" || typeof b === "boolean") return Boolean(a) === Boolean(b);
    return String(a ?? "").trim() === String(b ?? "").trim();
};

/**
 * Work out what an import row would actually change on an employee already on
 * record.
 *
 * Two rules, both of which exist so a partially-filled sheet is safe to import:
 *   - a blank cell is silence, not an instruction to clear the field
 *   - a value equal to what is stored is not a change, so it is not reported
 *
 * Nested objects are walked leaf by leaf and patched with dotted paths. Setting
 * `bankDetails` wholesale would wipe the branch name whenever the sheet left
 * that column empty.
 */
const buildPatch = (existing, incoming, prefix = "", patch = {}, changes = []) => {
    for (const [key, value] of Object.entries(incoming || {})) {
        if (key.startsWith("_")) continue;

        const path = prefix ? `${prefix}.${key}` : key;
        const current = existing?.[key];

        if (
            value &&
            typeof value === "object" &&
            !(value instanceof Date) &&
            !Array.isArray(value)
        ) {
            buildPatch(current || {}, value, path, patch, changes);
            continue;
        }

        if (isBlankValue(value)) continue;
        if (current !== undefined && sameValue(current, value)) continue;

        patch[path] = value;
        changes.push({ field: path, from: current ?? "", to: value });
    }

    return { patch, changes };
};

const normalizeEnum = (val, map) => map[String(val || "").toLowerCase().trim()] || "";

const GENDER_MAP = { male: "male", female: "female", other: "other" };
const MARITAL_MAP = { single: "single", married: "married", divorced: "divorced", widowed: "widowed" };
const EMP_TYPE_MAP = {
    permanent: "full_time", trainee: "intern", contract: "contract", intern: "intern",
    full_time: "full_time", "part time": "part_time", part_time: "part_time",
    "full time": "full_time",
};
const ACCT_TYPE_MAP = { savings: "savings", current: "current" };
const TITLE_MAP = {
    "mr.": "Mr.", mr: "Mr.", "mrs.": "Mrs.", mrs: "Mrs.",
    "ms.": "Ms.", ms: "Ms.", "dr.": "Dr.", dr: "Dr."
};

const fmtDate = (v) => {
    if (!v) return "";
    try {
        const d = new Date(v);
        if (isNaN(d.getTime())) return "";
        const dd = String(d.getDate()).padStart(2, "0");
        const mm = String(d.getMonth() + 1).padStart(2, "0");
        return `${dd}/${mm}/${d.getFullYear()}`;
    } catch { return ""; }
};

const capFirst = (s) => s ? s.charAt(0).toUpperCase() + s.slice(1).replace(/_/g, " ") : "";

/** Server-side canonical salary recalculation from Gross */
const recalcSalary = (gross, cfg) => {
    gross = Number(gross) || 0;
    const basicPct = (cfg.basicPct ?? 50) / 100;
    const hraPct = (cfg.hraPct ?? 50) / 100;
    const eepfPct = (cfg.eepfPct ?? 12) / 100;
    const epfCap = cfg.epfCapAmount ?? 1800;
    const edliPct = (cfg.edliPct ?? 0.5) / 100;
    const edliCap = cfg.edliCapAmount ?? 15000;
    const adminPct = (cfg.adminChargesPct ?? 0.5) / 100;
    const esiLimit = cfg.esiWageLimit ?? 21000;
    const eeEsicPct = (cfg.eeEsicPct ?? 0.75) / 100;
    const erEsicPct = (cfg.erEsicPct ?? 3.25) / 100;
    const food = cfg.foodAllowance ?? 1600;
    const basic = Math.round(gross * basicPct);
    const hra = Math.round(gross * hraPct);
    const epf = Math.round(Math.min(basic * eepfPct, epfCap));
    const edli = Math.round(Math.min(basic * edliPct, edliCap));
    const adminCharges = Math.round(basic * adminPct);
    const esiOk = basic <= esiLimit;
    const eeesic = esiOk ? Math.ceil(basic * eeEsicPct) : 0;
    const erEsic = esiOk ? Math.ceil(basic * erEsicPct) : 0;
    return {
        gross, basic, hra, epf,
        edli, edliOverride: false,
        adminCharges, adminOverride: false,
        eeesic, erEsic,
        foodAllowance: food,
        employerCost: gross + epf + erEsic + food,
        totalDeduction: epf + eeesic,
        netSalary: Math.max(gross - (epf + eeesic), 0),
        allowances: hra, deductions: epf + eeesic,
        specialAllowance: Math.max(gross - basic - hra, 0),
    };
};

const applyExtraField = (emp, meta, rawValue) => {
    if (rawValue === undefined || rawValue === null) return;
    const s = String(rawValue).trim();
    if (!s) return;
    let value;
    switch (meta.type) {
        case "date": value = parseDate(s); break;
        case "number": value = toNum(s); break;
        case "bool": value = toBool(s); break;
        case "enum": value = TITLE_MAP[s.toLowerCase()] ?? null; break;
        default: value = s;
    }
    if (value === undefined || value === null) return;
    if (typeof value !== "boolean" && value === "") return;
    if (meta.nested === "bankDetails") {
        emp.bankDetails[meta.field] = value;
    } else {
        emp[meta.field] = value;
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// PARSE SHEET (import)
// ─────────────────────────────────────────────────────────────────────────────
/**
 * Which row holds the column headers.
 *
 * The xlsx template puts them on row 3, under a banner and a section strip.
 * The CSV download starts at row 1, and people delete decoration rows. Rather
 * than hard-coding an offset and failing confusingly, score the first handful
 * of rows against the known column names and take the best match.
 */
const findHeaderRow = (sheet) => {
    const known = new Set(Object.keys(HEADER_MAP).map(normalizeHeader));
    const grid = XLSX.utils.sheet_to_json(sheet, {
        header: 1,
        raw: false,
        defval: "",
        blankrows: true,
    });

    let best = { row: 2, hits: 0 };
    const depth = Math.min(10, grid.length);

    for (let r = 0; r < depth; r++) {
        const hits = (grid[r] || []).reduce(
            (n, cellValue) => n + (known.has(normalizeHeader(cellValue)) ? 1 : 0),
            0,
        );
        if (hits > best.hits) best = { row: r, hits };
    }

    // Below a few matches this is guesswork; fall back to the documented layout
    // so the error message stays the familiar "wrong template" one.
    return best.hits >= 3 ? best.row : 2;
};

const parseSheet = async (buffer) => {
    const wb = XLSX.read(buffer, { type: "buffer", cellDates: true, raw: false });
    const sheet = wb.Sheets[wb.SheetNames[0]];

    // The export/template has:
    //   Row 1 = banner
    //   Row 2 = section colours
    //   Row 3 = column headers  ← range: 2 (0-based index 2 = row 3)
    //   Row 4+ = data
    // Find the header row rather than assuming it is the third. The xlsx
    // template puts it there under a banner and a section strip, but the CSV
    // download starts at the headers, and people delete decoration rows. The
    // row that matches the most known column names is the header row.
    const headerRow = findHeaderRow(sheet);

    const raw = XLSX.utils.sheet_to_json(sheet, { raw: false, defval: "", range: headerRow });
    if (!raw || raw.length === 0) {
        throw new Error("No data rows found. Make sure you are using the correct template.");
    }

    const normKeyMap = {};
    for (const key of Object.keys(raw[0])) {
        normKeyMap[normalizeHeader(key)] = key;
    }

    const standardNorms = new Set(Object.keys(HEADER_MAP).map(normalizeHeader));
    const extraColumns = [];
    for (const [normHeader, xlsxKey] of Object.entries(normKeyMap)) {
        if (standardNorms.has(normHeader)) continue;
        for (const [extraKey, meta] of Object.entries(EXTRA_FIELD_MAP)) {
            if (normalizeHeader(extraKey) === normHeader) {
                extraColumns.push({ normHeader, xlsxKey, meta });
                break;
            }
        }
    }

    if (extraColumns.length > 0) {
        console.log(`[Import] Detected ${extraColumns.length} extra column(s):`,
            extraColumns.map(c => `"${c.normHeader}" → ${c.meta.field}`).join(", "));
    }

    const cfg = await SalaryConfig.getSingleton();
    const rows = [];
    const errors = [];

    for (let i = 0; i < raw.length; i++) {
        const rawRow = raw[i];
        const allVals = Object.values(rawRow).map(v => String(v || "").trim());
        if (allVals.every(v => v === "")) continue;

        const row = {};
        for (const [rawHeader, fieldKey] of Object.entries(HEADER_MAP)) {
            if (fieldKey === "_skip") continue;
            const xlsxKey = normKeyMap[normalizeHeader(rawHeader)];
            row[fieldKey] = xlsxKey !== undefined ? String(rawRow[xlsxKey] ?? "").trim() : "";
        }

        const employeeNum = i + 1;
        const rowErrors = [];

        if (!row.employeeName) rowErrors.push("Employee Name is required");
        if (!row.biometricId) rowErrors.push("Biometric ID is required");
        if (!row.department) rowErrors.push("Department is required");
        if (!row.designation) rowErrors.push("Designation is required");
        if (!row.phone) rowErrors.push("Mobile Number is required");
        if (!row.gender) rowErrors.push("Gender is required");

        const nameParts = (row.employeeName || "").trim().split(/\s+/);
        const firstName = nameParts[0] || "";
        const lastName = nameParts.slice(1).join(" ") || "";

        const gross = toNum(row.grossSalary);
        const salary = recalcSalary(gross, cfg);

        const emp = {
            _employeeNum: employeeNum,
            _errors: rowErrors,
            _extraFields: extraColumns
                .map(c => ({ column: c.normHeader, field: c.meta.field, value: String(rawRow[c.xlsxKey] ?? "").trim() }))
                .filter(x => x.value),
            firstName,
            lastName,
            fatherFirstName: (row.fatherName || "").split(/\s+/)[0] || "",
            fatherLastName: (row.fatherName || "").split(/\s+/).slice(1).join(" ") || "",
            gender: normalizeEnum(row.gender, GENDER_MAP),
            dateOfBirth: parseDate(row.dateOfBirth),
            phone: row.phone || "",
            alternatePhone: row.alternatePhone || "",
            personalEmail: row.personalEmail || "",
            email: row.workEmail || "",
            maritalStatus: normalizeEnum(row.maritalStatus, MARITAL_MAP),
            bloodGroup: row.bloodGroup || "",
            nationality: row.nationality || "",
            // optBool, not toBool: an empty Yes/No cell must not flip a stored
            // true to false when this row updates an existing employee.
            isPhysicallyChallenged: optBool(row.physicallyChallenged),
            isDirector: optBool(row.isDirector),
            needsToOperate: optBool(row.needsToOperate),
            biometricId: row.biometricId || "",
            department: row.department || "",
            designation: row.designation || "",
            employmentType: normalizeEnum(row.employeeType, EMP_TYPE_MAP),
            // No default here — "GRAV Clothing" is applied only when creating.
            // Defaulting at parse time would overwrite a custom work location
            // every time someone re-imported a sheet with that column blank.
            workLocation: row.workLocation || "",
            shift: row.shift || "",
            dateOfJoining: parseDate(row.dateOfJoining),
            // Zero gross means the column was left empty. Sending a full set of
            // zeroed salary components would wipe the employee's real pay.
            salary: gross > 0 ? salary : undefined,
            bankDetails: {
                bankName: row.bankName || "",
                accountNumber: row.accountNumber || "",
                ifscCode: row.ifscCode || "",
                accountType: normalizeEnum(row.accountType, ACCT_TYPE_MAP),
                branchName: "",
            },
            documents: {
                aadharNumber: row.aadhaarNumber || "",
                panNumber: row.panNumber || "",
                uanNumber: row.uanNumber || "",
                esicNumber: row.esiNumber || "",
                pfNumber: row.pfNumber || "",
            },
            address: {
                current: {
                    street: row.currStreet || "", city: row.currCity || "",
                    state: row.currState || "", pincode: row.currPincode || "",
                    country: "India",
                },
                // Permanent is NOT mirrored from current here. It has its own
                // columns in the sheet (applied via EXTRA_FIELD_MAP), and
                // copying current over it would silently overwrite a different
                // permanent address on every re-import. The mirror still
                // happens, but only when creating a brand new employee.
            },
        };

        for (const { xlsxKey, meta } of extraColumns) {
            const rawValue = String(rawRow[xlsxKey] ?? "").trim();
            applyExtraField(emp, meta, rawValue);
        }

        rows.push(emp);
        if (rowErrors.length > 0) errors.push({ employeeNum, errors: rowErrors });
    }

    const extraDetected = extraColumns.map(c => ({ column: c.normHeader, schemaField: c.meta.field }));
    return { rows, errors, extraDetected };
};

// ─────────────────────────────────────────────────────────────────────────────
// MATCHING EXISTING EMPLOYEES
//
// An import is an upsert, not an insert. Re-importing an exported sheet — the
// obvious way to bulk-edit — used to create a second copy of everyone and then
// fail half of them on the unique index. A row that names someone already on
// record updates them instead.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Batch-resolve every row to an existing employee, returning a lookup function.
 *
 * Three queries rather than one per row, and matched in priority order:
 * Biometric ID is the sheet's identity column and is required, so it wins.
 * Identity ID and work email are fallbacks for sheets built elsewhere. They
 * are tried in sequence, never as one $or — an $or could match a DIFFERENT
 * person by email than the biometric ID names, and silently merge two records.
 */
const buildEmployeeMatcher = async (rows) => {
    const biometricIds = [...new Set(rows.map(r => r.biometricId).filter(Boolean))];
    const identityIds = [...new Set(rows.map(r => r.identityId).filter(Boolean))];
    const emails = [...new Set(rows.map(r => r.email).filter(Boolean))];

    const or = [];
    if (biometricIds.length) or.push({ biometricId: { $in: biometricIds } });
    if (identityIds.length) or.push({ identityId: { $in: identityIds } });
    if (emails.length) or.push({ email: { $in: emails } });

    const found = or.length ? await Employee.find({ $or: or }).lean() : [];

    const byBiometric = new Map();
    const byIdentity = new Map();
    const byEmail = new Map();

    for (const emp of found) {
        if (emp.biometricId) byBiometric.set(String(emp.biometricId), emp);
        if (emp.identityId) byIdentity.set(String(emp.identityId), emp);
        if (emp.email) byEmail.set(String(emp.email).toLowerCase(), emp);
    }

    return (row) => {
        if (row.biometricId && byBiometric.has(row.biometricId)) {
            return { employee: byBiometric.get(row.biometricId), matchedBy: "Biometric ID" };
        }
        if (row.identityId && byIdentity.has(row.identityId)) {
            return { employee: byIdentity.get(row.identityId), matchedBy: "Identity ID" };
        }
        const email = row.email ? String(row.email).toLowerCase() : "";
        if (email && byEmail.has(email)) {
            return { employee: byEmail.get(email), matchedBy: "Work Email" };
        }
        return null;
    };
};

/**
 * The employee-shaped object a parsed row describes.
 *
 * Shared by create and update so the two can never disagree about which sheet
 * column feeds which field.
 */
const toEmployeeData = (row) => ({
    firstName: row.firstName,
    lastName: row.lastName || "",
    fatherFirstName: row.fatherFirstName || undefined,
    fatherLastName: row.fatherLastName || undefined,
    fatherMiddleName: row.fatherMiddleName || undefined,
    motherFirstName: row.motherFirstName || undefined,
    motherLastName: row.motherLastName || undefined,
    title: ["Mr.", "Mrs.", "Ms.", "Dr."].includes(row.title) ? row.title : undefined,
    nickName: row.nickName || undefined,
    gender: row.gender || undefined,
    dateOfBirth: row.dateOfBirth || undefined,
    phone: row.phone || undefined,
    alternatePhone: row.alternatePhone || undefined,
    extension: row.extension || undefined,
    personalEmail: row.personalEmail || undefined,
    email: row.email || undefined,
    maritalStatus: row.maritalStatus || undefined,
    marriageDate: row.marriageDate || undefined,
    spouseName: row.spouseName || undefined,
    spouseDOB: row.spouseDOB || undefined,
    bloodGroup: row.bloodGroup || undefined,
    nationality: row.nationality || undefined,
    religion: row.religion || undefined,
    placeOfBirth: row.placeOfBirth || undefined,
    countryOfOrigin: row.countryOfOrigin || undefined,
    residentialStatus: row.residentialStatus || undefined,
    isPhysicallyChallenged: row.isPhysicallyChallenged,
    isDirector: row.isDirector,
    isInternational: row.isInternational,
    needsToOperate: row.needsToOperate,
    biometricId: row.biometricId || undefined,
    identityId: row.identityId || undefined,
    department: row.department || undefined,
    designation: row.designation || undefined,
    jobTitle: row.jobTitle || undefined,
    jobPosition: row.jobPosition || undefined,
    employmentType: row.employmentType || undefined,
    workLocation: row.workLocation || undefined,
    shift: row.shift || undefined,
    dateOfJoining: row.dateOfJoining || undefined,
    confirmationDate: row.confirmationDate || undefined,
    probationPeriod: row.probationPeriod || undefined,
    salary: row.salary,
    bankDetails: row.bankDetails,
    documents: row.documents,
    address: row.address,
    ...(row.primaryManagerName ? { primaryManager: { managerName: row.primaryManagerName } } : {}),
    ...(row.secondaryManagerName ? { secondaryManager: { managerName: row.secondaryManagerName } } : {}),
});

/**
 * Decide what each row will do, and what it will change.
 *
 * Required-field validation only applies to rows that will CREATE someone. A
 * row updating an existing employee has already been identified, so demanding
 * Department, Designation and Gender again would block the most useful case
 * there is: a two-column sheet of Biometric ID and the one field being filled
 * in across the workforce.
 */
const planRows = async (rows) => {
    const match = await buildEmployeeMatcher(rows);

    return rows.map((row) => {
        const hit = match(row);
        const incoming = toEmployeeData(row);

        if (!hit) {
            return {
                ...row,
                _mode: "create",
                _errors: row._errors || [],
                _changes: [],
            };
        }

        // Compare against DECRYPTED salary. The stored value is a cipher string
        // and the sheet's is a number, so without this every employee would
        // look like their pay had changed on every single import.
        const existing = decryptEmployeeDoc(hit.employee);
        const { patch, changes } = buildPatch(existing, incoming);

        return {
            ...row,
            _mode: "update",
            _errors: [],                     // identity resolved; nothing else is mandatory
            _existingId: String(hit.employee._id),
            _matchedBy: hit.matchedBy,
            _existingName: [hit.employee.firstName, hit.employee.lastName]
                .filter(Boolean).join(" "),
            _changes: changes,
            _patch: patch,
        };
    });
};

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 2: PREVIEW
// ─────────────────────────────────────────────────────────────────────────────
router.post("/import/preview", EmployeeAuthMiddlewear, upload.single("file"), async (req, res) => {
    try {
        if (!req.file) return res.status(400).json({ success: false, message: "No file uploaded." });

        const { rows: parsed, extraDetected } = await parseSheet(req.file.buffer);
        const rows = await planRows(parsed);

        // Errors are recomputed here, not taken from parseSheet: a row that
        // turned out to match an existing employee is no longer missing
        // anything, because it is not creating a record.
        const errors = rows
            .filter(r => r._errors.length > 0)
            .map(r => ({ employeeNum: r._employeeNum, errors: r._errors }));

        const toCreate = rows.filter(r => r._mode === "create");
        const toUpdate = rows.filter(r => r._mode === "update");
        const unchanged = toUpdate.filter(r => r._changes.length === 0);

        res.json({
            success: true,
            data: {
                total: rows.length,
                valid: rows.filter(r => r._errors.length === 0).length,
                invalid: errors.length,
                willCreate: toCreate.filter(r => r._errors.length === 0).length,
                willUpdate: toUpdate.length - unchanged.length,
                unchanged: unchanged.length,
                extraDetected,
                docUploadNote:
                    "Profile photos and scanned documents cannot be uploaded via Excel. " +
                    "After import, visit each employee's HRMS profile to upload their documents.",
                upsertNote:
                    "Rows matching an employee already on record will update them. " +
                    "Only the cells you filled in are applied — an empty cell is left " +
                    "alone and never clears an existing value.",
                rows,
                errors,
            },
        });
    } catch (err) {
        console.error("Import preview error:", err);
        res.status(500).json({ success: false, message: err.message || "Failed to parse file." });
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 3: CONFIRM IMPORT
// ─────────────────────────────────────────────────────────────────────────────
// A spreadsheet import is a bulk edit to employee records, and the one place
// where a mistake reaches hundreds of people at once. It gets its own section
// so it can be read as a list of imports rather than being scattered through
// the Employees history alongside single edits.
const { recordChange } = require("../../services/changeLog");

router.post("/import/confirm", EmployeeAuthMiddlewear, async (req, res) => {
    try {
        const { user } = req;
        const { rows } = req.body;
        if (!Array.isArray(rows) || rows.length === 0) {
            return res.status(400).json({ success: false, message: "No rows to import." });
        }

        const results = {
            created: 0,
            updated: 0,
            unchanged: 0,
            failed: 0,
            errors: [],
            updatedDetails: [],
        };

        // Re-planned server-side. The client sends back what preview gave it,
        // but the decision to create or update — and the patch that goes with
        // it — is not something to take on trust from a request body.
        const planned = await planRows(rows);

        for (const row of planned) {
            try {
                if (row._errors && row._errors.length > 0) {
                    results.failed++;
                    results.errors.push({ employeeNum: row._employeeNum, errors: row._errors });
                    continue;
                }

                /* ── UPDATE ─────────────────────────────────────────────── */
                if (row._mode === "update") {
                    const changed = Object.keys(row._patch || {});

                    if (changed.length === 0) {
                        results.unchanged++;
                        continue;
                    }

                    // Loaded and saved as a document rather than updateOne'd.
                    // updateOne skips the model's pre-save hook, which is what
                    // re-encrypts salary and recalculates the derived fields —
                    // a $set would have written plaintext numbers into columns
                    // every other part of the system expects to be encrypted.
                    const doc = await Employee.findById(row._existingId);
                    if (!doc) {
                        results.failed++;
                        results.errors.push({
                            employeeNum: row._employeeNum,
                            biometricId: row.biometricId,
                            errors: ["Employee disappeared between preview and import"],
                        });
                        continue;
                    }

                    for (const [fieldPath, value] of Object.entries(row._patch)) {
                        doc.set(fieldPath, value);
                    }
                    doc.updatedBy = user?.id;

                    await doc.save();

                    results.updated++;
                    results.updatedDetails.push({
                        employeeNum: row._employeeNum,
                        name: row._existingName,
                        biometricId: row.biometricId,
                        matchedBy: row._matchedBy,
                        fields: changed,
                    });
                    continue;
                }

                /* ── CREATE ─────────────────────────────────────────────── */
                const tempPass = Math.random().toString(36).slice(-8);
                const empData = toEmployeeData(row);

                // Create-time defaults. These deliberately do NOT run on update:
                // defaulting there would overwrite whatever is already on record
                // every time a column was left blank.
                empData.workLocation = empData.workLocation || "GRAV Clothing";
                empData.probationPeriod = empData.probationPeriod || 0;
                empData.isPhysicallyChallenged = empData.isPhysicallyChallenged || false;
                empData.isDirector = empData.isDirector || false;
                empData.isInternational = empData.isInternational || false;
                empData.needsToOperate = empData.needsToOperate || false;

                // A new joiner's permanent address defaults to their current one
                // unless the sheet gave a separate permanent address.
                const current = empData.address?.current;
                if (current && !empData.address.permanent?.street) {
                    empData.address.permanent = { ...current };
                }

                empData.password = tempPass;
                empData.temporaryPassword = tempPass;
                empData.createdBy = user?.id;
                empData.createdAt = new Date();

                const emp = new Employee(empData);
                await emp.save();
                results.created++;
            } catch (err) {
                results.failed++;
                const msg = err.code === 11000
                    ? `Duplicate: ${Object.keys(err.keyPattern || {}).join(", ")} already exists`
                    : err.message || "Unknown error";
                results.errors.push({
                    employeeNum: row._employeeNum,
                    biometricId: row.biometricId,
                    name: [row.firstName, row.lastName].filter(Boolean).join(" "),
                    errors: [msg],
                });
            }
        }

        const parts = [`${results.created} created`, `${results.updated} updated`];
        if (results.unchanged) parts.push(`${results.unchanged} already up to date`);
        if (results.failed) parts.push(`${results.failed} failed`);

        // Named per employee, with the fields the import touched on each. A
        // count alone cannot answer the question this log exists for: an
        // employee whose designation changed on the 14th needs to be able to
        // find that it was an import that did it, and which columns it wrote.
        await recordChange(req, {
            departmentSlug: "hr",
            section: "hr:employee-import",
            entity: "employee-import",
            entityId: new Date().toISOString(),
            entityLabel: `Import of ${rows.length} row(s)`,
            action: "import",
            origin: "import",
            summary:
                `Imported an employee spreadsheet of ${rows.length} row(s): ${parts.join(", ")}. ` +
                (results.failed
                    ? `The ${results.failed} failed row(s) changed nothing.`
                    : "Every row was processed."),
            fields: results.updatedDetails.slice(0, 120).map((d) => ({
                path: d.biometricId || String(d.employeeNum),
                label: `${d.name || d.biometricId} (matched by ${d.matchedBy})`,
                to: d.fields.join(", "),
                kind: "changed",
            })),
        });

        res.json({
            success: true,
            message: `Import complete: ${parts.join(", ")}.`,
            data: results,
        });
    } catch (err) {
        console.error("Import confirm error:", err);
        res.status(500).json({ success: false, message: err.message || "Import failed." });
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 4: EXPORT
// Produces a styled .xlsx that exactly mirrors the import template format.
// All auto-calc salary fields get live Excel formulas.
// Extra employee fields (passport, voter ID etc.) are written as extra columns
// appended after the standard block so they're preserved on re-import via
// the EXTRA_FIELD_MAP.
// ─────────────────────────────────────────────────────────────────────────────
// ── Extra columns appended after the standard block ────────────────────────
// These map directly to EXTRA_FIELD_MAP so re-import picks them up. Module
// scope, because /template and /export must emit the identical column set.
const EXTRA_EXPORT_COLS = [
            { header: "Job Title", getValue: e => e.jobTitle || "" },
            { header: "Nick Name", getValue: e => e.nickName || "" },
            { header: "Religion", getValue: e => e.religion || "" },
            { header: "Place of Birth", getValue: e => e.placeOfBirth || "" },
            { header: "Country of Origin", getValue: e => e.countryOfOrigin || "" },
            { header: "Residential Status", getValue: e => e.residentialStatus || "" },
            { header: "Is International", getValue: e => e.isInternational ? "Yes" : "No" },
            { header: "Spouse Name", getValue: e => e.spouseName || "" },
            { header: "Marriage Date", getValue: e => fmtDate(e.marriageDate) },
            { header: "Confirmation Date", getValue: e => fmtDate(e.confirmationDate) },
            { header: "Probation Period", getValue: e => e.probationPeriod ? String(e.probationPeriod) : "" },
            { header: "Identity ID", getValue: e => e.identityId || "" },
            { header: "Branch Name", getValue: e => e.bankDetails?.branchName || "" },
            { header: "Passport Number", getValue: e => e.documents?.passportNumber || "" },
            { header: "Voter ID", getValue: e => e.documents?.voterIdNumber || "" },
            { header: "Driving License", getValue: e => e.documents?.drivingLicenseNumber || "" },
            { header: "Primary Manager", getValue: e => e.primaryManager?.managerName || "" },
            { header: "Secondary Manager", getValue: e => e.secondaryManager?.managerName || "" },
            // Permanent address (separate from current in standard cols)
            { header: "Permanent Street", getValue: e => e.address?.permanent?.street || "" },
            { header: "Permanent City", getValue: e => e.address?.permanent?.city || "" },
            { header: "Permanent State", getValue: e => e.address?.permanent?.state || "" },
            { header: "Permanent Pincode", getValue: e => e.address?.permanent?.pincode || "" },
];

/**
 * Build the employee workbook from the shipped template.
 *
 * ONE builder for both the blank template and the populated export — that is
 * the point. When they were separate, the template drifted from what export
 * produced and an exported file could not be edited and re-imported.
 *
 * Two things forced a rewrite from the `xlsx` package to ExcelJS:
 *
 *   1. `xlsx` (the community build) SILENTLY DISCARDS cell styles on write.
 *      Every `s:` this file used to set was thrown away, which is why the
 *      download arrived unstyled no matter what the code asked for.
 *   2. The theme is not worth re-describing in code. The real template lives
 *      at assets/employee_import_template.xlsx and is loaded here, so
 *      restyling means editing that file — banner, section colours, borders,
 *      widths, freeze panes and the Instructions sheet all come along for
 *      free and cannot drift from what anyone expects to see.
 *
 * Salary formulas are regenerated for every row rather than copied from the
 * asset. The asset's first data row carried a broken set — it read Basic from
 * the row BELOW it, and Food Allowance, ESIC (Employer) and CTC were copies of
 * neighbouring cells — so copying would have propagated that into every row of
 * every export.
 *
 * @param employees  rows to write; empty for a template
 * @param cfg        salary config, drives the in-sheet formulas
 * @param mode       "template" | "export" — only changes the banner wording
 * @param blankRows  empty rows to pre-fill with formulas (template only)
 * @returns { buffer, csv }
 */
async function buildEmployeeWorkbook({ employees = [], cfg, mode = "export", blankRows = 0 }) {
    const isTemplate = mode === "template";

    // Salary arrives here already decrypted — callers must run the rows through
    // decryptEmployeeDocs() first. Handing over raw documents used to write the
    // "enc:…" cipher string into Gross Salary, which turned every formula that
    // reads it into #VALUE! all the way down the sheet. Fail loudly rather than
    // producing that file again.
    const stillEncrypted = employees.find(
        (e) => typeof e?.salary?.gross === "string" && e.salary.gross.startsWith("enc:"),
    );
    if (stillEncrypted) {
        throw new Error(
            "Salary is still encrypted — call decryptEmployeeDocs() on the employees " +
            "before building the workbook.",
        );
    }

    // A checked-in binary is easy to lose in a deploy that only ships source.
    // Say so plainly instead of letting ExcelJS throw an ENOENT that reaches
    // the user as a generic 500.
    if (!fs.existsSync(TEMPLATE_PATH)) {
        throw new Error(
            `Template asset missing at ${TEMPLATE_PATH}. It must be deployed with the code — ` +
            "the whole workbook design lives in that file.",
        );
    }

    const wb = new ExcelJS.Workbook();
    await wb.xlsx.readFile(TEMPLATE_PATH);

    const ws = wb.getWorksheet("Employee Import") || wb.worksheets[0];
    if (!ws) throw new Error("Template asset has no 'Employee Import' sheet.");

    /* ── Locate the header row rather than trusting an offset ─────────────── */
    const knownHeaders = new Set(COLUMNS.map((c) => normalizeHeader(c.header)));
    let headerRowNum = 3;
    let bestHits = 0;

    for (let r = 1; r <= Math.min(10, ws.rowCount); r++) {
        let hits = 0;
        ws.getRow(r).eachCell({ includeEmpty: false }, (cell) => {
            if (knownHeaders.has(normalizeHeader(cell.text))) hits++;
        });
        if (hits > bestHits) { bestHits = hits; headerRowNum = r; }
    }

    const dataStart = headerRowNum + 1;

    /* ── header text -> column number ─────────────────────────────────────── */
    const colOf = new Map();
    ws.getRow(headerRowNum).eachCell({ includeEmpty: false }, (cell, colNumber) => {
        colOf.set(normalizeHeader(cell.text), colNumber);
    });

    const copyStyle = (cell) =>
        cell && cell.style ? JSON.parse(JSON.stringify(cell.style)) : {};

    /* ── Capture the template's look before clearing anything ─────────────── */
    // Appended columns, and every row past the ones the asset already has, are
    // styled from these. Without them a 500-employee export would look like the
    // template for 100 rows and like raw Excel for the other 400.
    const templateColumnCount = ws.columnCount;
    const firstDataRow = ws.getRow(dataStart);
    const dataStyleByCol = new Map();
    for (let c = 1; c <= templateColumnCount; c++) {
        dataStyleByCol.set(c, copyStyle(firstDataRow.getCell(c)));
    }
    const headerStyle = copyStyle(ws.getRow(headerRowNum).getCell(1));
    const sectionStyle = copyStyle(ws.getRow(headerRowNum - 1).getCell(1));
    const plainDataStyle = dataStyleByCol.get(1) || {};

    /* ── Append the extra columns, in the template's own visual language ──── */
    // These carry fields with no home in the standard block: passport, voter
    // ID, permanent address, managers. They go into the TEMPLATE as well as the
    // export, so the two stay structurally identical — the thing that made
    // export → edit → re-import unreliable in the first place.
    const extraStartCol = COLUMNS.length + 1;
    const totalCols = COLUMNS.length + EXTRA_EXPORT_COLS.length;

    EXTRA_EXPORT_COLS.forEach((col, i) => {
        const c = extraStartCol + i;
        const cell = ws.getRow(headerRowNum).getCell(c);
        cell.value = col.header;
        cell.style = {
            ...headerStyle,
            fill: {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFEFF6FF" },
                bgColor: { argb: "FFDBEAFE" },
            },
            font: { ...(headerStyle.font || {}), color: { argb: "FF1E3A8A" } },
        };
        ws.getColumn(c).width = 18;
        colOf.set(normalizeHeader(col.header), c);
        dataStyleByCol.set(c, plainDataStyle);
    });

    // The banner spans the full width; the section strip gets an EXTRA INFO
    // block over the appended columns.
    try { ws.unMergeCells(1, 1, 1, templateColumnCount); } catch (e) { /* wasn't merged */ }
    ws.mergeCells(1, 1, 1, totalCols);
    ws.getRow(1).getCell(1).value = isTemplate
        ? "EMPLOYEE IMPORT TEMPLATE  •  Fields marked * are required  •  Enter Gross Salary — all other salary fields auto-calculate  •  Re-importing an existing Biometric ID updates that employee instead of creating a duplicate"
        : "EMPLOYEE EXPORT  •  Fields marked * are required on re-import  •  Enter Gross Salary — all other salary fields auto-calculate  •  Edit and re-import this file to update these employees";

    if (EXTRA_EXPORT_COLS.length > 0) {
        const banner = ws.getRow(headerRowNum - 1).getCell(extraStartCol);
        banner.value = "EXTRA INFO";
        banner.style = { ...sectionStyle };
        ws.mergeCells(headerRowNum - 1, extraStartCol, headerRowNum - 1, totalCols);
    }

    /* ── Clear the asset's own data rows ──────────────────────────────────── */
    if (ws.rowCount >= dataStart) {
        ws.spliceRows(dataStart, ws.rowCount - dataStart + 1);
    }

    /* ── Salary formulas ──────────────────────────────────────────────────── */
    const letterOf = (header) => {
        const c = colOf.get(normalizeHeader(header));
        return c ? ws.getColumn(c).letter : null;
    };

    const L = {
        gross: letterOf("Gross Salary"),
        basic: letterOf("Basic Salary"),
        hra: letterOf("HRA"),
        epfEE: letterOf("EPF (Employee)"),
        esicEE: letterOf("ESIC (Employee)"),
        totDed: letterOf("Total Deductions"),
        net: letterOf("Net Salary"),
        epfER: letterOf("EPF (Employer)"),
        esicER: letterOf("ESIC (Employer)"),
        food: letterOf("Food Allowance"),
        ctc: letterOf("Employer Cost (CTC)"),
    };

    const basicPct = (cfg.basicPct ?? 50) / 100;
    const hraPct = (cfg.hraPct ?? 50) / 100;
    const eepfPct = (cfg.eepfPct ?? 12) / 100;
    const epfCap = cfg.epfCapAmount ?? 1800;
    const esiLimit = cfg.esiWageLimit ?? 21000;
    const eeEsicPct = (cfg.eeEsicPct ?? 0.75) / 100;
    const erEsicPct = (cfg.erEsicPct ?? 3.25) / 100;
    const foodAmt = cfg.foodAllowance ?? 1600;

    // Every formula is guarded with IF(Gross="","",…) so a blank template row
    // stays visually empty instead of showing a column of zeroes.
    const formulasFor = (R) => ({
        [L.basic]: `IF(${L.gross}${R}="","",ROUND(${L.gross}${R}*${basicPct},0))`,
        [L.hra]: `IF(${L.gross}${R}="","",ROUND(${L.gross}${R}*${hraPct},0))`,
        [L.epfEE]: `IF(${L.basic}${R}="","",ROUND(MIN(${L.basic}${R}*${eepfPct},${epfCap}),0))`,
        [L.esicEE]: `IF(${L.basic}${R}="","",IF(${L.basic}${R}<=${esiLimit},CEILING(${L.basic}${R}*${eeEsicPct},1),0))`,
        [L.totDed]: `IF(${L.epfEE}${R}="","",${L.epfEE}${R}+IF(${L.esicEE}${R}="",0,${L.esicEE}${R}))`,
        [L.net]: `IF(${L.gross}${R}="","",MAX(${L.gross}${R}-IF(${L.totDed}${R}="",0,${L.totDed}${R}),0))`,
        [L.epfER]: `IF(${L.epfEE}${R}="","",${L.epfEE}${R})`,
        [L.esicER]: `IF(${L.basic}${R}="","",IF(${L.basic}${R}<=${esiLimit},CEILING(${L.basic}${R}*${erEsicPct},1),0))`,
        [L.food]: `IF(${L.gross}${R}="","",${foodAmt})`,
        [L.ctc]: `IF(${L.gross}${R}="","",${L.gross}${R}+IF(${L.epfER}${R}="",0,${L.epfER}${R})+IF(${L.esicER}${R}="",0,${L.esicER}${R})+IF(${L.food}${R}="",0,${L.food}${R}))`,
    });

    const FORMULA_HEADERS = new Set(
        ["Basic Salary", "HRA", "EPF (Employee)", "ESIC (Employee)", "Total Deductions",
            "Net Salary", "EPF (Employer)", "ESIC (Employer)", "Food Allowance",
            "Employer Cost (CTC)"].map(normalizeHeader)
    );

    /* ── Write the rows ───────────────────────────────────────────────────── */
    const writeRow = (offset, employee) => {
        const emp = employee || {};
        const isBlankRow = !employee;
        const rowNum = dataStart + offset;
        const row = ws.getRow(rowNum);

        const fatherFullName = [emp.fatherFirstName, emp.fatherMiddleName, emp.fatherLastName]
            .filter(Boolean).join(" ");

        const VALUES = {
            "Employee Name": `${emp.firstName || ""} ${emp.lastName || ""}`.trim(),
            "Title": emp.title || "",
            "Father / Husband Name": fatherFullName,
            "Gender": capFirst(emp.gender || ""),
            "Date of Birth": fmtDate(emp.dateOfBirth),
            "Mobile Number": emp.phone || "",
            "Alternate Phone": emp.alternatePhone || "",
            "Personal Email": emp.personalEmail || "",
            "Work Email": emp.email || "",
            "Marital Status": capFirst(emp.maritalStatus || ""),
            "Blood Group": emp.bloodGroup || "",
            "Nationality": emp.nationality || "",
            "Physically Challenged": isBlankRow ? "" : (emp.isPhysicallyChallenged ? "Yes" : "No"),
            "Street / Area": emp.address?.current?.street || "",
            "City": emp.address?.current?.city || "",
            "State": emp.address?.current?.state || "",
            "Pincode": emp.address?.current?.pincode || "",
            "Biometric ID": emp.biometricId || "",
            "Date of Joining": fmtDate(emp.dateOfJoining),
            "Department": emp.department || "",
            "Designation": emp.designation || "",
            "Employee Type": capFirst(emp.employmentType || ""),
            "Work Location": emp.workLocation || "",
            "Shift": emp.shift || "",
            "Is Director": isBlankRow ? "" : (emp.isDirector ? "Yes" : "No"),
            "Needs to Operate": isBlankRow ? "" : (emp.needsToOperate ? "Yes" : "No"),
            "Bank Name": emp.bankDetails?.bankName || "",
            "Account Number": emp.bankDetails?.accountNumber || "",
            "IFSC Code": emp.bankDetails?.ifscCode || "",
            "Account Type": capFirst(emp.bankDetails?.accountType || ""),
            // Blank, not 0 — the formulas key off Gross being empty, and a
            // template full of zeroes would compute a full set of zero
            // deductions instead of staying quiet.
            "Gross Salary": isBlankRow ? "" : (emp.salary?.gross || 0),
            "Aadhaar Number": emp.documents?.aadharNumber || "",
            "PAN Number": emp.documents?.panNumber || "",
            "UAN Number": emp.documents?.uanNumber || "",
            "ESI Number": emp.documents?.esicNumber || "",
            "PF Number": emp.documents?.pfNumber || "",
        };

        const rowFormulas = formulasFor(rowNum);

        COLUMNS.forEach((col) => {
            const c = colOf.get(normalizeHeader(col.header));
            if (!c) return;

            const cell = row.getCell(c);
            cell.style = dataStyleByCol.get(c) || plainDataStyle;

            if (FORMULA_HEADERS.has(normalizeHeader(col.header))) {
                const letter = ws.getColumn(c).letter;
                if (rowFormulas[letter]) cell.value = { formula: rowFormulas[letter] };
                return;
            }

            const v = VALUES[col.header];
            cell.value = v === undefined || v === "" ? null : v;
        });

        EXTRA_EXPORT_COLS.forEach((col, i) => {
            const c = extraStartCol + i;
            const cell = row.getCell(c);
            cell.style = dataStyleByCol.get(c) || plainDataStyle;
            const v = isBlankRow ? "" : col.getValue(emp);
            cell.value = v === undefined || v === "" ? null : v;
        });

        row.height = 18;
        row.commit();
    };

    employees.forEach((emp, i) => writeRow(i, emp));
    for (let i = 0; i < blankRows; i++) writeRow(employees.length + i, null);

    /* ── Widen columns to fit what is actually in them ────────────────────── */
    // The template's widths were set for a blank sheet. Once real data is in
    // it, names, emails, addresses and manager names get cut off mid-word, so
    // every column grows to its longest value. It only ever grows: the
    // template's width is the floor, so a deliberately wide column stays wide.
    const MIN_WIDTH = 10;
    const MAX_WIDTH = 46;   // past this a column stops being scannable

    for (let c = 1; c <= totalCols; c++) {
        const column = ws.getColumn(c);
        let longest = 0;

        column.eachCell({ includeEmpty: false }, (cell, rowNumber) => {
            // The row-1 banner spans every column; measuring it would blow the
            // first column out to the width of the whole sentence.
            if (rowNumber < headerRowNum) return;

            let text = cell.value;
            if (text && typeof text === "object") {
                if (text.formula !== undefined) text = text.result ?? "";
                else if (text.richText) text = text.richText.map((t) => t.text).join("");
                else if (text.text !== undefined) text = text.text;
                else text = "";
            }
            const len = String(text ?? "").length;
            if (len > longest) longest = len;
        });

        const fitted = Math.min(MAX_WIDTH, Math.max(MIN_WIDTH, longest + 3));
        column.width = Math.max(column.width || 0, fitted);
    }

    /* ── Output ───────────────────────────────────────────────────────────── */
    const buffer = Buffer.from(await wb.xlsx.writeBuffer());

    // CSV of the data only, from the header row down — the banner and section
    // strip are decoration and would leave a CSV reader with two junk lines
    // before the headers.
    //
    // Formula cells have no computed result until Excel opens the file, so the
    // auto-calculated salary columns come through blank here. Harmless: the
    // importer recalculates them from Gross anyway.
    const csvEscape = (s) => (/[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s);
    const csvLines = [];

    for (let r = headerRowNum; r <= ws.rowCount; r++) {
        const row = ws.getRow(r);
        const values = [];

        for (let c = 1; c <= totalCols; c++) {
            let v = row.getCell(c).value;
            if (v instanceof Date) v = fmtDate(v);
            else if (v && typeof v === "object") {
                if (v.formula !== undefined) v = v.result ?? "";
                else if (v.richText) v = v.richText.map((t) => t.text).join("");
                else if (v.text !== undefined) v = v.text;
                else v = "";
            }
            values.push(csvEscape(v === null || v === undefined ? "" : String(v)));
        }

        if (r > headerRowNum && values.every((v) => v === "")) continue;
        csvLines.push(values.join(","));
    }

    return { buffer, csv: csvLines.join("\n") };
}

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 4: EXPORT
// ─────────────────────────────────────────────────────────────────────────────
router.get("/export", EmployeeAuthMiddlewear, async (req, res) => {
    try {
        const { department, status, search } = req.query;

        let filter = {};
        if (department && department !== "all") filter.department = department;
        if (status && status !== "all") filter.status = status;
        if (search) {
            filter.$or = [
                { firstName: { $regex: search, $options: "i" } },
                { lastName: { $regex: search, $options: "i" } },
                { email: { $regex: search, $options: "i" } },
                { biometricId: { $regex: search, $options: "i" } },
            ];
        }

        const rawEmployees = await Employee.find(filter).sort({ createdAt: -1 }).lean();

        // Salary is stored encrypted ("enc:a1b2…"). Writing the raw field put
        // ciphertext in the Gross Salary column, and every formula that reads
        // it — Basic, HRA, EPF, ESIC, Net, CTC — then showed #VALUE! down the
        // whole sheet.
        const employees = decryptEmployeeDocs(rawEmployees);

        const cfg = await SalaryConfig.getSingleton();

        const built = await buildEmployeeWorkbook({ employees, cfg, mode: "export" });

        const dateStr = new Date().toISOString().split("T")[0];

        if (String(req.query.format || "").toLowerCase() === "csv") {
            res.setHeader("Content-Disposition", `attachment; filename=employee_export_${dateStr}.csv`);
            res.setHeader("Content-Type", "text/csv; charset=utf-8");
            return res.send(built.csv);
        }

        assertRealWorkbook(built.buffer, "export");

        res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate");
        res.setHeader("Content-Disposition", `attachment; filename=employee_export_${dateStr}.xlsx`);
        res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        res.setHeader("Content-Length", built.buffer.length);
        return res.send(built.buffer);

    } catch (err) {
        console.error("Export error:", err);
        res.status(500).json({ success: false, message: err.message || "Export failed." });
    }
});

module.exports = router;
// Exposed for tests: the template being a broken file is the kind of bug that
// only shows up when someone opens it, so it is worth being able to build one
// without standing up the whole app.
module.exports.buildEmployeeWorkbook = buildEmployeeWorkbook;
// The merge rules decide whether a re-import enriches records or wipes them,
// so they are worth being able to assert on directly.
module.exports.buildPatch = buildPatch;