// models/Accountant_model/Acc_GSTR2B.js
// =============================================================================
// GSTR-2B IMPORT STORAGE
// -----------------------------------------------------------------------------
// Stores parsed GSTR-2B JSON files downloaded by the accountant from the GST
// portal. One document per (company, return period). Each document holds the
// full list of invoice/credit-note records from the 2B JSON, flattened from
// the nested GSTN schema for query-friendly access.
//
// The 2B file is a "static" return (locked once generated by GSTN for a given
// month), so re-uploading the same period replaces the prior import — the
// upsert is keyed on (companyId, returnPeriod, ctin... ).
//
// SCHEMA REFERENCE (GSTN GSTR-2B JSON v1.0):
//   data
//     gstin              ← taxpayer's own GSTIN (us, the buyer)
//     rtnprd             ← return period like "042026" (MMYYYY)
//     gendt              ← generation date
//     itcsumm            ← summary totals
//     docdata
//       b2b[]            ← supplier-grouped invoices
//         ctin           ← supplier's GSTIN
//         trdnm          ← supplier trade name
//         inv[]          ← invoice list under this supplier
//           inum, dt, val, iamt, camt, samt, csamt, itcavl, rsn, ...
//       b2ba[]           ← amendments to b2b
//       cdnr[]           ← credit/debit notes (nt[] holds the notes)
//       cdnra[]          ← amendments to credit/debit notes
//       impg[]           ← imports of goods
//       impgsez[]        ← imports from SEZ
//       isd[]            ← input service distributor
//
// We flatten this on import into a single `records[]` array with a `section`
// discriminator. Reconciliation queries then run as plain array filters or
// (when the dataset is large) as Mongoose aggregations on the parent doc.
// =============================================================================

const mongoose = require("mongoose");

// Single flattened record — one invoice / credit-note / etc.
const gstr2bRecordSchema = new mongoose.Schema(
  {
    // Which 2B section this record belongs to. Reconciliation logic treats
    // b2b / b2ba / cdnr / cdnra differently (amendments override originals;
    // credit notes invert sign).
    section: {
      type: String,
      enum: ["b2b", "b2ba", "cdnr", "cdnra", "impg", "impgsez", "isd", "isda"],
      required: true,
      index: true,
    },

    // Supplier identity (the counterparty)
    supplierGSTIN: { type: String, trim: true, uppercase: true, index: true },
    supplierName: { type: String, trim: true },

    // Document fields
    docNumber: { type: String, trim: true }, // inum (B2B) or ntnum (CDNR)
    docDate: { type: Date }, // dt → Date
    docType: { type: String, trim: true }, // "Regular", "SEZWP", "DE", etc.
    noteType: { type: String, trim: true }, // "C" (credit) / "D" (debit) for CDNR

    // Financial fields
    taxableValue: { type: Number, default: 0 }, // val
    cgst: { type: Number, default: 0 }, // camt
    sgst: { type: Number, default: 0 }, // samt
    igst: { type: Number, default: 0 }, // iamt
    cess: { type: Number, default: 0 }, // csamt
    invoiceValue: { type: Number, default: 0 }, // total including tax (for B2B); computed if absent

    // ITC eligibility flags from GSTN
    itcAvailable: { type: Boolean, default: true }, // "Y"/"N" → boolean
    itcUnavailReason: { type: String, trim: true }, // rsn — populated when itcAvailable=false

    // GSTR-1 filing status of the supplier (helps spot late filers)
    supplierFilingStatus: { type: String, trim: true },
    supplierFilingDate: { type: Date },
    supplierReturnPeriod: { type: String, trim: true }, // rtnprd of supplier's GSTR-1

    // Place of supply
    placeOfSupply: { type: String, trim: true }, // pos
    reverseCharge: { type: Boolean, default: false }, // rev = "Y"/"N"

    // IMS (Invoice Management System) action — newer; may be absent on older 2B
    imsAction: { type: String, trim: true }, // "A"/"R"/"P"/"NA"

    // For amendments — the original document being amended
    originalDocNumber: { type: String, trim: true },
    originalDocDate: { type: Date },

    // Free-form raw payload for fields we don't model explicitly. Keeps the
    // door open for future drill-down without re-importing.
    raw: { type: mongoose.Schema.Types.Mixed },
  },
  { _id: false },
);

const acc_GSTR2B_schema = new mongoose.Schema(
  {
    // Multi-company support — same convention as the rest of the accountant module
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Acc_Company",
      required: true,
      index: true,
    },

    // Which return type produced this data. 2B and 2A are nearly identical in
    // JSON shape (same docdata.b2b/cdnr/impg/isd structure) but serve different
    // purposes: 2B is the LOCKED monthly statement (canonical), 2A is the
    // REAL-TIME running view that keeps changing until 2B locks. We store
    // both in the same collection but tag the source so the UI can label and
    // filter them. A company may have BOTH a 2A and a 2B for the same period
    // (e.g. before the 14th lock date).
    //
    // The collection name `Acc_GSTR2B` is kept for backward compatibility
    // with existing data; the model now handles both 2A and 2B.
    returnType: {
      type: String,
      enum: ["GSTR2B", "GSTR2A"],
      default: "GSTR2B",
      required: true,
      index: true,
    },

    // Our (taxpayer's) GSTIN from the file. Sanity-checked against the company
    // record on import; mismatch → reject the upload so the wrong file can't
    // contaminate another company's reconciliation.
    taxpayerGSTIN: {
      type: String,
      trim: true,
      uppercase: true,
      required: true,
    },

    // Return period in MMYYYY (matching GSTN's `rtnprd` exactly). Example: "042026"
    // for April 2026. We keep it as a string so the GSTN format is preserved
    // and the original JSON can be re-exported losslessly.
    returnPeriod: { type: String, trim: true, required: true, index: true },

    // Derived: month/year as numbers for easier UI filtering & sorting
    periodMonth: { type: Number, min: 1, max: 12, required: true },
    periodYear: { type: Number, required: true },

    // GSTN's generation date — different from our import date. The 2B is
    // generated on the 14th of the following month typically.
    generationDate: { type: Date },

    // When WE imported the file (and which accountant did it)
    importedAt: { type: Date, default: Date.now },
    importedBy: { type: String, trim: true }, // accountant email
    importedFilename: { type: String, trim: true },

    // Summary totals straight from the file's `itcsumm` block — useful for
    // a quick "did the file parse fully?" sanity check vs sum of records.
    summaryTotals: {
      itcAvailable: {
        cgst: { type: Number, default: 0 },
        sgst: { type: Number, default: 0 },
        igst: { type: Number, default: 0 },
        cess: { type: Number, default: 0 },
      },
      itcUnavailable: {
        cgst: { type: Number, default: 0 },
        sgst: { type: Number, default: 0 },
        igst: { type: Number, default: 0 },
        cess: { type: Number, default: 0 },
      },
    },

    // All flattened records (B2B + CDNR + amendments + imports + ISD)
    records: { type: [gstr2bRecordSchema], default: [] },

    // Bookkeeping: any non-fatal warnings encountered during parse
    importWarnings: { type: [String], default: [] },

    // ── Cached reconciliation result ───────────────────────────────────────
    // Reconciliation against the books is a non-trivial query (potentially
    // thousands of voucher rows joined per-supplier). We cache the last result
    // so reopening the GST page is instant — the accountant can then click
    // "Refresh" to recompute when they want fresh numbers.
    //
    // Cache invalidation:
    //   • Automatic when re-uploading 2B for the same period (the doc is
    //     replaced via upsert, dropping these fields by default).
    //   • Manual via the Refresh button on the recon section UI.
    //   • Never goes stale by time — the accountant decides what counts as
    //     "current enough"; we just record `lastReconAt` so they can judge.
    lastReconAt: { type: Date },
    lastReconBy: { type: String, trim: true }, // accountant email
    lastReconSummary: { type: mongoose.Schema.Types.Mixed }, // small summary { matched: {count, totalTax}, ...}
    lastReconBuckets: { type: mongoose.Schema.Types.Mixed }, // full buckets — only loaded on demand
    lastReconTolerance: {
      amount: { type: Number, default: 1 },
      days: { type: Number, default: 3 },
    },
  },
  { timestamps: true },
);

// Unique constraint: one file per (company, period, type). Re-uploading the
// same type for the same period replaces. A company can hold a 2A and a 2B
// for April 2026 simultaneously — they're different sources.
acc_GSTR2B_schema.index(
  { companyId: 1, returnPeriod: 1, returnType: 1 },
  { unique: true },
);

// Fast supplier-wise lookup on a single 2B document
acc_GSTR2B_schema.index({ "records.supplierGSTIN": 1 });

const Acc_GSTR2B = mongoose.model("Acc_GSTR2B", acc_GSTR2B_schema);

module.exports = { Acc_GSTR2B };
